version: '3.8'
services:
    redis-new:
        image: redis:latest
        restart: always
        container_name: redis-new
        ports:
            - '6380:6379'
        volumes:
            - redis_data:/data
        networks:
            - beckn_action_bot_network

    beckn-action-bot:
        image: mayurvirendra/beckn-action-bot:latest
        restart: always
        container_name: beckn-action-bot
        build: .
        env_file: ./.env
        environment:
            - REDIS_URL=redis://redis-new:6379
        ports:
            - '${PORT}:${PORT}'
            - ${SERVER_PORT}:${SERVER_PORT}
        depends_on:
            - redis-new
        networks:
            - beckn_action_bot_network
        volumes:
            - ./:/app

volumes:
    index_data:
        driver: local
    backups:
        driver: local
    redis_data:
        driver: local

networks:
    beckn_action_bot_network:
