name: Run unit tests

on:
    push:
        branches-ignore:
            - main
jobs:
    test-lint:
        name: Unit tests
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up environment variables
              run: |
                  echo "OPENAI_AI_KEY=${{secrets.OPENAI_AI_KEY}}" >> .env
                  echo "OPENAI_MODEL_ID=${{secrets.OPENAI_MODEL_ID}}" >> .env
                  echo "OPEN_AI_EMBEDDINGS_MODEL=${{secrets.OPEN_AI_EMBEDDINGS_MODEL}}" >> .env
                  echo "PORT=${{secrets.PORT}}" >> .env
                  echo "SERVER_PORT=${{secrets.SERVER_PORT}}" >> .env
                  echo "TWILIO_ACCOUNT_SID=${{secrets.TWILIO_ACCOUNT_SID}}" >> .env
                  echo "TWILIO_AUTH_TOKEN=${{secrets.TWILIO_AUTH_TOKEN}}" >> .env
                  echo "TWILIO_NUMBER=${{secrets.TWILIO_NUMBER}}" >> .env
                  echo "TEST_RECEPIENT_NUMBER=${{secrets.TEST_RECEPIENT_NUMBER}}" >> .env
                  echo "STRAPI_TOURISM_TOKEN=${{secrets.STRAPI_TOURISM_TOKEN}}" >> .env
                  echo "GOOGLE_MAPS_API_KEY=${{secrets.GOOGLE_MAPS_API_KEY}}" >> .env
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run unit tests
              run: npm run docker:test:unit
